CREATE WAREHOUSE IF NOT EXISTS WEATHER_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.ANALYTICS;
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;
SHOW WAREHOUSES;
ALTER ACCOUNT SET TIMEZONE = 'Asia/Manila';


SELECT
    warehouse_name,
    ROUND(SUM(credits_used), 4) AS total_credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY warehouse_name
ORDER BY total_credits DESC;

CREATE RESOURCE MONITOR IF NOT EXISTS WEATHER_MONITOR
  WITH CREDIT_QUOTA = 10
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WEATHER_WH SET RESOURCE_MONITOR = WEATHER_MONITOR;
ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = WEATHER_MONITOR;

SHOW RESOURCE MONITORS;
SHOW WAREHOUSES;

ALTER WAREHOUSE SNOWFLAKE_LEARNING_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE SNOWFLAKE_LEARNING_WH SET RESOURCE_MONITOR = WEATHER_MONITOR;

SHOW WAREHOUSES;