CREATE WAREHOUSE IF NOT EXISTS WEATHER_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.ANALYTICS;
SHOW WAREHOUSES;