USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ANALYST;

GRANT USAGE ON WAREHOUSE WEATHER_WH TO ROLE ANALYST;

GRANT USAGE ON DATABASE WEATHER_DB TO ROLE ANALYST;

GRANT USAGE ON SCHEMA WEATHER_DB.ANALYTICS TO ROLE ANALYST;

GRANT SELECT ON ALL VIEWS IN SCHEMA WEATHER_DB.ANALYTICS TO ROLE ANALYST;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA WEATHER_DB.ANALYTICS TO ROLE ANALYST;

GRANT ROLE ANALYST TO USER MELVINLICAROS03;

USE ROLE ANALYST;
USE WAREHOUSE WEATHER_WH;

SELECT COUNT(*) FROM WEATHER_DB.ANALYTICS.WEATHER_HOURLY;

SELECT *
FROM WEATHER_DB.RAW.WEATHER_RAW;

USE ROLE ACCOUNTADMIN;

USE SECONDARY ROLES NONE;
SELECT COUNT(*) FROM WEATHER_DB.ANALYTICS.WEATHER_HOURLY;
SELECT * FROM WEATHER_DB.RAW.WEATHER_RAW;

USE SECONDARY ROLES ALL;
USE ROLE ACCOUNTADMIN;